"""units

Revision ID: 1b465d3dba36
Revises: 5ade169d042b
Create Date: 2020-09-05 23:06:08.166248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b465d3dba36'
down_revision = '5ade169d042b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('oob', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oob'], ['order_of_battle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    # ### end Alembic commands ###
