"""Setting up FK

Revision ID: 2079c8542307
Revises: 68a9274448dc
Create Date: 2020-09-05 22:09:05.102578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2079c8542307'
down_revision = '68a9274448dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_of_battle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'players', ['player'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_of_battle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('player')

    # ### end Alembic commands ###
