"""about me

Revision ID: 53725f32798e
Revises: 6fd809d42db9
Create Date: 2020-09-06 16:50:09.263660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53725f32798e'
down_revision = '6fd809d42db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
