"""Setting up FK for oob

Revision ID: 69d304b73c0e
Revises: 2079c8542307
Create Date: 2020-09-05 22:14:50.387019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d304b73c0e'
down_revision = '2079c8542307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oob', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_units_oob_order_of_battle'), 'order_of_battle', ['oob'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_units_oob_order_of_battle'), type_='foreignkey')
        batch_op.drop_column('oob')

    # ### end Alembic commands ###
