"""battlelog

Revision ID: 6fd809d42db9
Revises: 1b465d3dba36
Create Date: 2020-09-05 23:06:31.177832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd809d42db9'
down_revision = '1b465d3dba36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('attacker', sa.String(length=80), nullable=True),
    sa.Column('defender', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_log')
    # ### end Alembic commands ###
